config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root "home#index"

  get "/home", to: "home#index"

  get "/users", to: "users#index"
  get "/users/sign_up", to: "users#new"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"

  get "/sessions/new", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions/:id", to: "sessions#destroy", as: "sessions_destroy"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new"
  get "/posts/:id", to: "posts#show", as: "post"
  post "/posts", to: "posts#create"
  delete "/posts/:id", to: "posts#destroy", as: "delete_post"


  post "/posts/:post_id/comments", to: "comments#create"

  resources :payments, only: %i[new]

  post "payments/create" 
  get "payments/success"
  get "payments/cancel"

  resources :plans, only: %i[new]
  post "plans/create"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

# if current_user&.subscription&.active?
#   if current_user.subscription.posts_allowed.nil?
#     @posts = Post.all
#   else
#     @posts = Post.limit(current_user.subscription.posts_allowed)
#   end
# elsif current_user.present?
#   redirect_to new_payment_path, alert: "Please subscribe to view posts"
# else
#   @posts = [] # or show some public content or teaser here
# end





# if current_user.subscription&.active?
#   if current_user.subscription.posts_allowed.nil?
#     @posts = Post.all
#   else
#     @posts = Post.limit(current_user.subscription.posts_allowed)
#   end
# else
#   redirect_to new_payment_path, alert: "Please subscribe to view posts"
# end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<nav class="navbar bg-secondary d-flex justify-content-between">
   <%= image_tag "logo.png", size: "105x55", class: "rounded-circle ms-2"%>
   <% if !current_user.present? %>
      <div class = "me-2">
         <%= link_to "SignUp", users_sign_up_path,  class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
         <%= link_to "SignIn", sessions_new_path,  class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
      </div>
   <% else %>
      <h1 class = "fs-3 mt-2 ps-2">Welcome to Posts, <%= current_user.name %></h1>
      <div class = "d-flex" >
         <%= link_to "My Posts", posts_path, class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
         <%= button_to "Signout", sessions_destroy_path(current_user), method: :delete, class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
      </div>
   <% end %>
</nav>

<% if current_user.present?%>
   <h1 class = "fs-3 m-1 my-2 fw-bold text-danger feed">Your feed</h1>
   <div class="row row-cols-4 g-3 p-2"> 
      <!-- all posts -->
      <% @posts.each do |post| %>
         <div class="col">
            <!-- each post -->
            <div class="text-center p-2 rounded" style="background-color: #93939366;">
               <div class="d-flex flex-start align-items-center gap-2 ms-2 mt-1 mb-4">
                  <%= image_tag "profile-user.png", size: "30x30", class:"rounded-circle" %>
                  <p class="mb-0 "><%= post.user.name %></p>
               </div>
               <%= image_tag "post.jpg", size: "140x130", class:"rounded" %>
               <h1 class="fs-5 text-truncate pt-2 my-2"><%= post.title %></h1>
               <%= link_to "View post", post, class: "btn btn-primary fs-5-sm mt-3 text-decoration-none text-white" %>
            </div>
         </div>
      <% end %>
   </div>
<% else %>
   <h1 class = "fs-2 m-4" >Login to see posts</h1>
<% end %>