config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root "home#index"

  get "/home", to: "home#index"

  get "/users", to: "users#index"
  get "/users/sign_up", to: "users#new"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"

  get "/sessions/new", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions/:id", to: "sessions#destroy", as: "sessions_destroy"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new"
  get "/posts/:id", to: "posts#show", as: "post"
  post "/posts", to: "posts#create"
  delete "/posts/:id", to: "posts#destroy", as: "delete_post"


  post "/posts/:post_id/comments", to: "comments#create"

  resources :payments, only: %i[new]

  post "payments/create" 
  get "payments/success"
  get "payments/cancel"

  resources :plans, only: %i[new]
  post "plans/create"
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new 
  end

  def create

    # plan = params[:plan]
    # plans = {
    #   "basic" => { price: "price_1RBsWV13kpId3pWt4dFlHtA2", posts_allowed: 5 },
    #   "standard" => { price: "price_1RBsWu13kpId3pWttjrn5jk6", posts_allowed: 12 },
    #   "premium" => { price: "price_1RBsXF13kpId3pWtPEUYSLY4", posts_allowed: nil } # nil = no limit user can see all posts
    # }

    @plan = Plan.find_by(name: params[:plan])

    customer = Stripe::Customer.create(
        name: current_user.name,
        email: current_user.email,
        description: "Customer id: #{current_user.id}",
    )

    session = Stripe::Checkout::Session.create(
      customer: customer,
      payment_method_types: ['card'],
      line_items: [{
      # price: plans[plan][:price],
        price: @plan.stripe_price_id,
        quantity: 1
      }],
      mode: 'subscription',
      success_url: payments_success_url(plan: @plan),
      cancel_url: payments_cancel_url
    )

    redirect_to session.url, allow_other_host: true
  end

  def success
    # plan = params[:plan]
    # post_limits = { "basic" => 5, "standard" => 12, "premium" => nil }
    # posts_allowed = post_limits[plan]

    @plan = Plan.find(params[:plan])
    current_user.create_subscription!(
      posts_allowed: @plan.posts_allowed,
      stripe_price_id: @plan.name,
      active: true
    )

    redirect_to root_path, notice: "Subscription activated!"
  end

  def cancel
    redirect_to root_url, alert: "Purchase Unsuccessful"
  end

end


# THIS ACTION(LOGIC) IS FOR "PAYMENT" NOT FOR "SUBSCRIPTION"

# def create 
#    #create stripe customer for payment, update if already created
#    customer = Stripe::Customer.create(
#          name: current_user.name,
#          email: current_user.email,
#       description: "Customer id: #{current_user.id}",
#    )

#    session = Stripe::Checkout::Session.create( 
#       customer: customer, 
#       payment_method_types: ['card'],
#       line_items: [{
#          price: 'price_1RBZxM13kpId3pWttq4DG29r',
#          quantity: 1,
#          }],
#          mode: 'payment',
#          success_url:  payments_success_url,
#          cancel_url: payments_cancel_url
#       )
#       redirect_to session.url, allow_other_host: true
#    end
# end      
      
# def success
#    #handle successful payments
#    redirect_to root_url, notice: "Purchase Successful"
# end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<nav class="navbar bg-secondary d-flex justify-content-between">
   <%= image_tag "logo.png", size: "105x55", class: "rounded-circle ms-2"%>
      <% if !current_user.present? %>
      <h1 class = "fs-3 mt-2 ps-2">Welcome to Posts</h1>
      <div class = "me-2">
         <%= link_to "SignUp", users_sign_up_path,  class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
         <%= link_to "SignIn", sessions_new_path,  class: "text-center btn btn-danger fs-5 m-1 text-decoration-none text-white" %>
      </div>
   <% else %>
      <h1 class = "fs-3 mt-2 ps-2">Welcome to Posts, <%= current_user.name%></h1>
      <div class = "d-flex" >
         <%= button_to "Signout", sessions_destroy_path(current_user), method: :delete, class: "text-center btn btn-danger fs-5 m-1" %>
      </div>
   <% end %>

</nav>

<div class="w-100 d-flex justify-content-center mt-4">
   <div class="w-25 text-center px-2 ">
      <p class="fs-2 fw-bold lh-1">Choose Your Favorite Pacakage.</p>
   </div>
</div>

<p class="fw-lighter text-center fs-5-sm">Select one of your favorite package and get the facilities.</p>
<h5 class="text-center pb-2 d-flex justify-content-center align-items-center"><span class = "text-danger fs-2 pe-2">«</span> Monthly <span class = "text-danger fs-2 ps-2">»</span></h5>

<div class="w-100">
   <div class="mx-3 d-flex justify-items-center justify-content-center">
      <div class = "row row-cols-4 g-2">
         <% @plan_ids = Plan.ids %> 
         <% @plan_ids.each do |id| %>
            <div class = "col">
               <% plan = Plan.find(id) %>
               <div class="border border-danger m-2 mt-3 rounded p-4">
                  <p class="fs-4 fw-bold m-1"><%= plan.name.titleize.gsub(/[_-]/, " ") %></p> 
                  <div class="bg-danger rounded" style="height: 2px; width: 200px;"></div> 

                  <div class="d-flex align-items-center mt-4">
                     <h5 class = "p-1 fw-light">₹</h5>
                     <h2><%= plan.price_in_rupees %>.00/-</h2>
                  </div>

                  <div class = "mt-3">
                     <div class="d-flex aligned-items-center">
                        <%= image_tag "checked.png", size: "20x20", class: "my-0"%>
                        <p class="fs-5-xsm fw-lighter ps-2">Create up to <b><%= plan.posts_allowed %></b> posts per month</p>
                     </div>
                     <div class="d-flex aligned-items-center">
                        <%= image_tag "checked.png", size: "20x20", class: "my-0"%>
                        <p class="fs-5-xsm fw-lighter ps-2">Perfect for power users</p>
                     </div>
                     <div class="d-flex aligned-items-center">
                        <%= image_tag "checked.png", size: "20x20", class: "my-0"%>
                        <p class="fs-5-xsm fw-lighter ps-2">Billed monthly</p>
                     </div>
                     <div class="d-flex aligned-items-center">
                        <%= image_tag "checked.png", size: "20x20", class: "my-0"%>
                        <p class="fs-5-xsm fw-lighter ps-2">Upgrade or cancel anytime</p>
                     </div>
                  </div>

                  <%= button_to "Get Started", payments_create_path(plan: plan.name ), method: :post, class: "btn btn-danger my-2 text-white text-decoration-none fs-5" %>

               </div>
            </div>
         <% end %>
      </div>
   </div>
</div>