config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root "home#index"

  get "/home", to: "home#index"

  get "/users", to: "users#index"
  get "/users/sign_up", to: "users#new"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"

  get "/sessions/new", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions/:id", to: "sessions#destroy", as: "sessions_destroy"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new"
  get "/posts/:id", to: "posts#show", as: "post"
  post "/posts", to: "posts#create"
  delete "/posts/:id", to: "posts#destroy", as: "delete_post"


  post "/posts/:post_id/comments", to: "comments#create"

  resources :payments, only: %i[new]

  post "payments/create" 
  get "payments/success"
  get "payments/cancel"

  resources :plans, only: %i[new]
  post "plans/create"
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum:3, maximum:50}

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  # PostCleanupJob.set(wait: 30.day).perform_later

  def self.clean 
    PostCleanupJob.perform_later
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(user_id: current_user.id)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @comments = @post.comments #all comments of that perticular @post
    @comment = @post.comments.build #model of creating comment
  end

  def new
    if current_user&.subscription&.active?
      if current_user.subscription.posts_allowed.nil?
        @post = current_user.posts.new
      elsif current_user.posts.count < current_user.subscription.posts_allowed
        @post = current_user.posts.new
      else
        flash[:alert] = "Post creating limit exceeded!!"
        redirect_to posts_path
      end 
    else 
      redirect_to new_payment_path
    end 
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save 
      redirect_to root_path, notice: "Post created successfully"
    else 
      flash[:alert] = "something went wrong, while creating post!" 
      render :new
    end 

    # if current_user&.subscription&.active?
    #   if current_user.subscription.posts_allowed.nil?
    #     @post = current_user.posts.new(post_params)
    #     if @post.save 
    #       redirect_to root_path, notice: "Post created successfully"
    #     else 
    #       flash[:alert] = "something went wrong, while creating post!" 
    #       render :new
    #     end 
    #   elsif current_user.posts.count <= current_user.subscription.posts_allowed
    #     @post = current_user.posts.new(post_params)
    #     if @post.save 
    #       redirect_to root_path, notice: "Post created successfully"
    #     else 
    #       flash[:alert] = "something went wrong, while creating post!" 
    #       render :new
    #     end 
    #   else
    #     flash[:alert] = "Members only! Please buy subscription..."
    #     redirect_to root_path
    #   end 
    # end 
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      if @post.destroy
        flash[:notice] = 'Post was successfully deleted.'
        redirect_to posts_url
      else
        flash[:alert] = 'Something went wrong'
        redirect_to posts_url
      end
    else 
      flash[:alert] = 'You are not authorized to delete this post!'
      redirect_to @post
    end 
  end
  
  def post_params
    params.require(:post).permit(:title, :content)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<nav class="d-flex navbar bg-secondary">
   <%= link_to "New Post", posts_new_path, class: "text-center btn btn-danger fs-5-sm ms-2 text-decoration-none text-white" %>
   <%= link_to "Back", home_path, class: "text-center btn btn-dark fs-5-sm me-2 text-decoration-none text-white" %>
</nav>
<div class= "d-flex flex-start align-items-center gap-2 p-1 mt-2 mb-3">
   <%= image_tag "profile-user.png", size: "30x30", class: "rounded-circle " %>
   <p class = "mb-0 fs-5" ><%= current_user.name %></p>
</div>

<div class="d-flex">
   <% if @posts.length < 1%>
      <p class = "fs-3 m-2 fw-bold text-danger">No post available, Please add a post..</p>
   <% else %>
      <div class="row row-cols-4 g-3 p-2">
      <% @posts.each do |post| %>
         <div class="col">
            <div class="bg-secondary bg-opacity-50 rounded p-3 h-100 w-100">
            <div class="d-flex justify-content-center">
               <%= image_tag "post.jpg", size: "140x130", class: "img-fluid rounded" %>
            </div>
            <h1 class="fs-5 text-truncate text-center pt-3"><%= post.title %></h1>
            <div class="d-flex justify-content-center mt-3">
               <%= link_to "View post", post, class: "btn btn-primary fs-6 text-white text-decoration-none" %>
            </div>
            </div>
         </div>
      <% end %>
      </div>
   <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
   <div class="editor mx-auto w-75 d-flex flex-column text-secondary bg-dark border-secondary p-4 shadow-lg rounded">
      <p class="text-center fw-bold fs-2 m-3 pb-4 text-warning">New Post</p>
      <form action= "/posts" method= "post">
         <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
         <input class="form-control mb-3 fs-4" name = "post[title]" placeholder="Title" type="text">
         <textarea class="form-control mb-3 fs-4" name = "post[content]" placeholder="Describe everything about this post here" rows="6"></textarea>

         <%= link_to "Cancel", root_path, class: "btn btn-dark my-3 fs-4" %>
         <button class="btn btn-warning fs-4 fw-bold" style="color: #121417 !important;">Post</button>

      </form>
   </div>
</div>

app/views/posts/show.html.erb
<div class="card d-flex align-items-start text-start w-50 bg-secondary mx-auto p-4 pt-3 mt-5">
   <%= image_tag "logo.png", size: "125x75", class: "rounded-circle ms-2 mb-3"%>

   <div class="card-body">
      <div class="card-img-top"><%= image_tag "post.jpg", size: "150x150" %></div>
      <h3 class="card-title my-2"><b>Title: </b> <%= @post.title %></h3>
      <p class="card-text fs-4"><b>Content: </b><%= @post.content %></p>
      <div class = "fs-5-sm pt-3" >
         <p class = " mb-0">Created by: <%= @user.name%></p>
         <p class = "">On: <%= @post.created_at.strftime("%B %d, %Y")%></p>
      </div>
   </div>
   <div class = "d-flex">
      <%= link_to "Back", posts_path, class: "btn btn-dark  fs-5 text-decoration-none text-white" %>
      <%= button_to "Delete", delete_post_path(@post),method: :delete, class: "btn btn-danger fs-5 d-inline-block mx-2" %>
   </div>

</div>

<p class = "fs-2">Comments:</p>
<% if @comments.any? %>
   <ul>
      <% @comments.each do |comment| %>
         <li class = "fs-5 text-warning"><%= comment.content %> (User: <%= comment.user_id%>)</li>
      <% end %>
   </ul>
<%end %>

<%= form_with model: @comment, url: "/posts/#{@post.id}/comments", method: :post do |f| %>
   <%= f.text_field :content, class: "form-control", placeholder: "Add comment here.." %>
   <%= f.submit class: "btn btn-primary" %>
<% end %>